Raise "unsupported operation" error when "pointer" is used as origin for key and wheel input sources
w3c/webdriver pull request #1760
Opened 2023-09-04 15:58 UTC by whimboo

Short term fix for issue #1758 to raise a specific failure for unsupported origin types in `get coordinates relative to an origin`.

2023-09-04 16:14 UTC, whimboo commented
@jgraham can you please review? Thanks!

2023-09-05 14:10 UTC, jgraham requested changes

2023-09-05 21:08 UTC, whimboo commented on index.html
> +    <ol>
That's actually a better idea, yes. We should not half-wise perform an action and then fail. Thanks for the suggestion! Please have a look if the updated code better suites what you thought of.

2023-09-07 08:29 UTC, jgraham approved these changes

2023-09-07 08:31 UTC, merged