Update user prompt handler note for fallbackDefault
w3c/webdriver pull request #1831
Opened 2024-07-16 22:27 UTC by juliandescottes

- Update the note to reflect the fact that "default" now applies to before unload and mention fallbackDefault
- fix `get the prompt handler` to select fallbackDefault when relevant

2024-07-16 22:27 UTC, juliandescottes commented
cc @jgraham

2024-07-19 14:19 UTC, jgraham requested changes

2024-07-19 14:19 UTC, jgraham commented on index.html
> +unhandled prompt behavior is a <a data-cite=infra>map</a> wgucg
```suggestion
unhandled prompt behavior is a <a data-cite=infra>map</a> which
```

2024-07-23 11:02 UTC, jgraham approved these changes

2024-07-23 11:02 UTC, merged